
# If you modify this file, you must run the command "pub get".

# See https://www.dartlang.org/tools/pub/pubspec#name
# WARNING:
#
#    The value of this parameter is used in the "import" statements.
#    If you modify the value of this parameter, make sure to propagate the modification in all your sources that require it.
name: myapp
description: This application illustrates the one way binding from data to view.

# version: 1.0.0
# homepage: https://www.example.com
# author: denis <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0
  angular_components: ^0.9.0

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
