// This file is the entry point for the application.

import 'package:angular/angular.dart';

// The file "app_component.template.dart" will be generated by the command "webdev serve".
// Location: .dart_tool/build/generated/my_first_app/lib/app_component.template.dart
// The content if this file is built from the annotations that precede the
// definition of the class "AppComponent" (in the file "lib/app_component.dart").
// See: https://webdev.dartlang.org/api/angular/angular/ComponentFactory-class
import 'package:myapp/app_component.template.dart' as ng;

main() {
  // The class "AppComponentNgFactory" has been generated by the command "webdev serve".
  // See: https://webdev.dartlang.org/api/angular/angular/ComponentFactory-class
  runApp(ng.AppComponentNgFactory);
}