name: myapp
description: Myapp
version: 0.0.1
environment:
  # See https://webdev.dartlang.org/tools/sdk
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  # See https://pub.dartlang.org/packages/angular
  angular: ^5.2.0
  # See https://pub.dartlang.org/packages/angular_forms
  angular_forms: ^2.1.1
dev_dependencies:
  angular_test: ^2.0.0-beta+2
  # See https://pub.dartlang.org/packages/build_runner
  build_runner: ^1.1.2
  build_test: ^0.10.3+1
  build_web_compilers: ^0.4.1
  pageloader: ^3.0.0-beta
  test: ^1.3.0
